#!/bin/bash
<<C
`job2.sh` - stores the system processes (like top's output) into a file every n-minutes.
It uses `ps` (for making a snapshot of current processes) with flag arguments for formatting of the output.

C

ps -eo user,pid,%cpu,%mem,bsdstart,args f > ~/.term_log3
date=`date`
echo "# " >> ~/.term_log3
echo "# $date" >> ~/.term_log3

# or without the f flag
# ps -eo user,pid,%cpu,%mem,bsdstart,args >> /home/mnost/.term_log3

# alternativelly
# ps auxf > ~/.term_log3


